# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY README.md ./
COPY server.py ./
COPY main.py ./
COPY webhook.py ./
COPY LICENSE ./
COPY uv.lock ./

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir "flask>=3.1.0" "httpx>=0.28.1" "jsonify>=0.5" "mcp[cli]>=1.4.1"

# Set default command to run the MCP server
CMD ["python", "server.py"]
